// Package errno holds errno codes for linux
package syserror

// Errno represents a Linux errno value.
type Errno uint32

// Errno values from include/uapi/asm-generic/errno-base.h.
const (
	LOC_NOERRNO = iota
	LOC_EPERM
	LOC_ENOENT
	LOC_ESRCH
	LOC_EINTR
	LOC_EIO
	LOC_ENXIO
	LOC_E2BIG
	LOC_ENOEXEC
	LOC_EBADF
	LOC_ECHILD // 10
	LOC_EAGAIN
	LOC_ENOMEM
	LOC_EACCES
	LOC_EFAULT
	LOC_ENOTBLK
	LOC_EBUSY
	LOC_EEXIST
	LOC_EXDEV
	LOC_ENODEV
	LOC_ENOTDIR // 20
	LOC_EISDIR
	LOC_EINVAL
	LOC_ENFILE
	LOC_EMFILE
	LOC_ENOTTY
	LOC_ETXTBSY
	LOC_EFBIG
	LOC_ENOSPC
	LOC_ESPIPE
	LOC_EROFS // 30
	LOC_EMLINK
	LOC_EPIPE
	LOC_EDOM
	LOC_ERANGE
	LOC_ // Errno values from include/uapi/asm-generic/errno.h.
	LOC_EDEADLK
	LOC_ENAMETOOLONG
	LOC_ENOLCK
	LOC_ENOSYS
	LOC_ENOTEMPTY
	LOC_ELOOP  // 40
	_          // Skip for EWOULDBLOCK = EAGAIN.
	LOC_ENOMSG //42
	LOC_EIDRM
	LOC_ECHRNG
	LOC_EL2NSYNC
	LOC_EL3HLT
	LOC_EL3RST
	LOC_ELNRNG
	LOC_EUNATCH
	LOC_ENOCSI
	LOC_EL2HLT // 50
	LOC_EBADE
	LOC_EBADR
	LOC_EXFULL
	LOC_ENOANO
	LOC_EBADRQC
	LOC_EBADSLT
	_ // Skip for EDEADLOCK = EDEADLK.
	LOC_EBFONT
	LOC_ENOSTR // 60
	LOC_ENODATA
	LOC_ETIME
	LOC_ENOSR
	_ // Skip for ENOENT = ENONET.
	LOC_ENOPKG
	LOC_EREMOTE
	LOC_ENOLINK
	LOC_EADV
	LOC_ESRMNT
	LOC_ECOMM // 70
	LOC_EPROTO
	LOC_EMULTIHOP
	LOC_EDOTDOT
	LOC_EBADMSG
	LOC_EOVERFLOW
	LOC_ENOTUNIQ
	LOC_EBADFD
	LOC_EREMCHG
	LOC_ELIBACC
	LOC_ELIBBAD // 80
	LOC_ELIBSCN
	LOC_ELIBMAX
	LOC_ELIBEXEC
	LOC_EILSEQ
	LOC_ERESTART
	LOC_ESTRPIPE
	LOC_EUSERS
	LOC_ENOTSOCK
	LOC_EDESTADDRREQ
	LOC_EMSGSIZE // 90
	LOC_EPROTOTYPE
	LOC_ENOPROTOOPT
	LOC_EPROTONOSUPPORT
	LOC_ESOCKTNOSUPPORT
	LOC_EOPNOTSUPP
	LOC_EPFNOSUPPORT
	LOC_EAFNOSUPPORT
	LOC_EADDRINUSE
	LOC_EADDRNOTAVAIL
	LOC_ENETDOWN // 100
	LOC_ENETUNREACH
	LOC_ENETRESET
	LOC_ECONNABORTED
	LOC_ECONNRESET
	LOC_ENOBUFS
	LOC_EISCONN
	LOC_ENOTCONN
	LOC_ESHUTDOWN
	LOC_ETOOMANYREFS
	LOC_ETIMEDOUT // 110
	LOC_ECONNREFUSED
	LOC_EHOSTDOWN
	LOC_EHOSTUNREACH
	LOC_EALREADY
	LOC_EINPROGRESS
	LOC_ESTALE
	LOC_EUCLEAN
	LOC_ENOTNAM
	LOC_ENAVAIL
	LOC_EISNAM // 120
	LOC_EREMOTEIO
	LOC_EDQUOT
	LOC_ENOMEDIUM
	LOC_EMEDIUMTYPE
	LOC_ECANCELED
	LOC_ENOKEY
	LOC_EKEYEXPIRED
	LOC_EKEYREVOKED
	LOC_EKEYREJECTED
	LOC_EOWNERDEAD // 130
	LOC_ENOTRECOVERABLE
	LOC_ERFKILL
	LOC_EHWPOISON
)
